object Form2: TForm2
  Left = 443
  Top = 114
  BorderStyle = bsSingle
  Caption = #1052#1086#1076#1077#1083#1100' '#1087#1086#1083#1077#1090#1072' '#1041#1056
  ClientHeight = 618
  ClientWidth = 704
  Color = cl3DDkShadow
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 13
  object RadioButton1: TRadioButton
    Left = 8
    Top = 568
    Width = 113
    Height = 17
    Caption = 'r'
    Checked = True
    Color = cl3DDkShadow
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'MS Sans Serif'
    Font.Style = [fsBold]
    ParentColor = False
    ParentFont = False
    TabOrder = 0
    TabStop = True
    OnClick = RadioButton1Click
  end
  object RadioButton2: TRadioButton
    Left = 120
    Top = 568
    Width = 105
    Height = 17
    Caption = 'Fi'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'MS Sans Serif'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 1
    OnClick = RadioButton2Click
  end
  object RadioButton3: TRadioButton
    Left = 232
    Top = 568
    Width = 105
    Height = 17
    Caption = 'V'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'MS Sans Serif'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 2
    OnClick = RadioButton3Click
  end
  object RadioButton4: TRadioButton
    Left = 344
    Top = 568
    Width = 105
    Height = 17
    Caption = 'Teta'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'MS Sans Serif'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 3
    OnClick = RadioButton4Click
  end
  object Chart2: TChart
    Left = 0
    Top = 0
    Width = 705
    Height = 553
    BackWall.Brush.Color = clWhite
    BackWall.Brush.Style = bsClear
    LeftWall.Color = clBlue
    Title.Font.Charset = DEFAULT_CHARSET
    Title.Font.Color = clGreen
    Title.Font.Height = -11
    Title.Font.Name = 'Arial'
    Title.Font.Style = [fsBold]
    Title.Text.Strings = (
      'Fi')
    BottomAxis.ExactDateTime = False
    BottomAxis.Increment = 0.2
    BottomAxis.LabelStyle = talValue
    LeftAxis.ExactDateTime = False
    LeftAxis.Increment = 0.01
    LeftAxis.LabelStyle = talValue
    Legend.Visible = False
    View3D = False
    TabOrder = 4
    Visible = False
    object Series2: TLineSeries
      Marks.ArrowLength = 8
      Marks.Visible = False
      SeriesColor = clRed
      LinePen.Width = 2
      Pointer.InflateMargins = True
      Pointer.Style = psRectangle
      Pointer.Visible = False
      XValues.DateTime = False
      XValues.Name = 'X'
      XValues.Multiplier = 1
      XValues.Order = loAscending
      YValues.DateTime = False
      YValues.Name = 'Y'
      YValues.Multiplier = 1
      YValues.Order = loNone
    end
  end
  object Chart3: TChart
    Left = 0
    Top = 0
    Width = 705
    Height = 553
    BackWall.Brush.Color = clWhite
    BackWall.Brush.Style = bsClear
    LeftWall.Color = clRed
    Title.Font.Charset = DEFAULT_CHARSET
    Title.Font.Color = clGreen
    Title.Font.Height = -11
    Title.Font.Name = 'Arial'
    Title.Font.Style = [fsBold]
    Title.Text.Strings = (
      'V')
    BottomAxis.ExactDateTime = False
    BottomAxis.Increment = 0.2
    BottomAxis.LabelStyle = talValue
    LeftAxis.ExactDateTime = False
    LeftAxis.Increment = 0.01
    LeftAxis.LabelStyle = talValue
    Legend.Visible = False
    View3D = False
    TabOrder = 5
    Visible = False
    object Series3: TLineSeries
      Marks.ArrowLength = 8
      Marks.Visible = False
      SeriesColor = clRed
      LinePen.Width = 2
      Pointer.InflateMargins = True
      Pointer.Style = psRectangle
      Pointer.Visible = False
      XValues.DateTime = False
      XValues.Name = 'X'
      XValues.Multiplier = 1
      XValues.Order = loAscending
      YValues.DateTime = False
      YValues.Name = 'Y'
      YValues.Multiplier = 1
      YValues.Order = loNone
    end
  end
  object Chart4: TChart
    Left = 0
    Top = 0
    Width = 705
    Height = 553
    BackWall.Brush.Color = clWhite
    BackWall.Brush.Style = bsClear
    LeftWall.Color = clRed
    Title.Font.Charset = DEFAULT_CHARSET
    Title.Font.Color = clGreen
    Title.Font.Height = -11
    Title.Font.Name = 'Arial'
    Title.Font.Style = [fsBold]
    Title.Text.Strings = (
      'Teta')
    BottomAxis.ExactDateTime = False
    BottomAxis.Increment = 0.2
    BottomAxis.LabelStyle = talValue
    LeftAxis.Automatic = False
    LeftAxis.AutomaticMaximum = False
    LeftAxis.AutomaticMinimum = False
    LeftAxis.ExactDateTime = False
    LeftAxis.Increment = 0.01
    LeftAxis.LabelStyle = talValue
    LeftAxis.Maximum = 1.8
    LeftAxis.Minimum = 0.7
    Legend.Visible = False
    View3D = False
    TabOrder = 6
    Visible = False
    object Series4: TLineSeries
      Marks.ArrowLength = 8
      Marks.Visible = False
      SeriesColor = clRed
      LinePen.Width = 2
      Pointer.InflateMargins = True
      Pointer.Style = psRectangle
      Pointer.Visible = False
      XValues.DateTime = False
      XValues.Name = 'X'
      XValues.Multiplier = 1
      XValues.Order = loAscending
      YValues.DateTime = False
      YValues.Name = 'Y'
      YValues.Multiplier = 1
      YValues.Order = loNone
    end
  end
  object RadioButton6: TRadioButton
    Left = 8
    Top = 592
    Width = 105
    Height = 17
    Caption = 'h'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'MS Sans Serif'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 7
    OnClick = RadioButton6Click
  end
  object RadioButton5: TRadioButton
    Left = 456
    Top = 568
    Width = 105
    Height = 17
    Caption = 'Alfa'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'MS Sans Serif'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 8
    OnClick = RadioButton5Click
  end
  object Chart5: TChart
    Left = 0
    Top = 0
    Width = 705
    Height = 553
    BackWall.Brush.Color = clWhite
    BackWall.Brush.Style = bsClear
    Title.Font.Charset = DEFAULT_CHARSET
    Title.Font.Color = clGreen
    Title.Font.Height = -11
    Title.Font.Name = 'Arial'
    Title.Font.Style = [fsBold]
    Title.Text.Strings = (
      'Alfa')
    BottomAxis.ExactDateTime = False
    BottomAxis.Increment = 0.2
    BottomAxis.LabelStyle = talValue
    LeftAxis.ExactDateTime = False
    LeftAxis.Increment = 0.01
    LeftAxis.LabelStyle = talValue
    Legend.Visible = False
    View3D = False
    TabOrder = 9
    Visible = False
    object Series5: TLineSeries
      Marks.ArrowLength = 8
      Marks.Visible = False
      SeriesColor = clRed
      LinePen.Width = 2
      Pointer.InflateMargins = True
      Pointer.Style = psRectangle
      Pointer.Visible = False
      XValues.DateTime = False
      XValues.Name = 'X'
      XValues.Multiplier = 1
      XValues.Order = loAscending
      YValues.DateTime = False
      YValues.Name = 'Y'
      YValues.Multiplier = 1
      YValues.Order = loNone
    end
  end
  object Chart6: TChart
    Left = 0
    Top = 0
    Width = 705
    Height = 553
    BackWall.Brush.Color = clWhite
    BackWall.Brush.Style = bsClear
    Title.Font.Charset = DEFAULT_CHARSET
    Title.Font.Color = clGreen
    Title.Font.Height = -11
    Title.Font.Name = 'Arial'
    Title.Font.Style = [fsBold]
    Title.Text.Strings = (
      'h')
    BottomAxis.ExactDateTime = False
    BottomAxis.Increment = 0.2
    BottomAxis.LabelStyle = talValue
    LeftAxis.ExactDateTime = False
    LeftAxis.Increment = 0.01
    LeftAxis.LabelStyle = talValue
    Legend.Visible = False
    View3D = False
    TabOrder = 10
    Visible = False
    object Series6: TLineSeries
      Marks.ArrowLength = 8
      Marks.Visible = False
      SeriesColor = clRed
      LinePen.Width = 2
      Pointer.InflateMargins = True
      Pointer.Style = psRectangle
      Pointer.Visible = False
      XValues.DateTime = False
      XValues.Name = 'X'
      XValues.Multiplier = 1
      XValues.Order = loAscending
      YValues.DateTime = False
      YValues.Name = 'Y'
      YValues.Multiplier = 1
      YValues.Order = loNone
    end
  end
  object Chart8: TChart
    Left = 0
    Top = 0
    Width = 705
    Height = 553
    BackWall.Brush.Color = clWhite
    BackWall.Brush.Style = bsClear
    Title.Font.Charset = DEFAULT_CHARSET
    Title.Font.Color = clGreen
    Title.Font.Height = -11
    Title.Font.Name = 'Arial'
    Title.Font.Style = [fsBold]
    Title.Text.Strings = (
      'q')
    BottomAxis.ExactDateTime = False
    BottomAxis.Increment = 0.2
    BottomAxis.LabelStyle = talValue
    LeftAxis.ExactDateTime = False
    LeftAxis.Increment = 0.01
    LeftAxis.LabelStyle = talValue
    Legend.Visible = False
    View3D = False
    TabOrder = 11
    object LineSeries2: TLineSeries
      Marks.ArrowLength = 8
      Marks.Visible = False
      SeriesColor = clRed
      LinePen.Width = 2
      Pointer.InflateMargins = True
      Pointer.Style = psRectangle
      Pointer.Visible = False
      XValues.DateTime = False
      XValues.Name = 'X'
      XValues.Multiplier = 1
      XValues.Order = loAscending
      YValues.DateTime = False
      YValues.Name = 'Y'
      YValues.Multiplier = 1
      YValues.Order = loNone
    end
  end
  object RadioButton8: TRadioButton
    Left = 120
    Top = 592
    Width = 113
    Height = 17
    Caption = 'q'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'MS Sans Serif'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 12
    OnClick = RadioButton8Click
  end
  object Chart9: TChart
    Left = 0
    Top = 0
    Width = 705
    Height = 553
    BackWall.Brush.Color = clWhite
    BackWall.Brush.Style = bsClear
    Title.Font.Charset = DEFAULT_CHARSET
    Title.Font.Color = clGreen
    Title.Font.Height = -11
    Title.Font.Name = 'Arial'
    Title.Font.Style = [fsBold]
    Title.Text.Strings = (
      'nx')
    BottomAxis.ExactDateTime = False
    BottomAxis.Increment = 0.2
    BottomAxis.LabelStyle = talValue
    LeftAxis.ExactDateTime = False
    LeftAxis.Increment = 0.01
    LeftAxis.LabelStyle = talValue
    Legend.Visible = False
    View3D = False
    TabOrder = 13
    object LineSeries3: TLineSeries
      Marks.ArrowLength = 8
      Marks.Visible = False
      SeriesColor = clRed
      LinePen.Width = 2
      Pointer.InflateMargins = True
      Pointer.Style = psRectangle
      Pointer.Visible = False
      XValues.DateTime = False
      XValues.Name = 'X'
      XValues.Multiplier = 1
      XValues.Order = loAscending
      YValues.DateTime = False
      YValues.Name = 'Y'
      YValues.Multiplier = 1
      YValues.Order = loNone
    end
  end
  object RadioButton9: TRadioButton
    Left = 232
    Top = 592
    Width = 113
    Height = 17
    Caption = 'nx'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'MS Sans Serif'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 14
    OnClick = RadioButton9Click
  end
  object RadioButton10: TRadioButton
    Left = 344
    Top = 592
    Width = 113
    Height = 17
    Caption = 'ny'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'MS Sans Serif'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 15
    OnClick = RadioButton10Click
  end
  object Chart10: TChart
    Left = 0
    Top = 0
    Width = 705
    Height = 553
    BackWall.Brush.Color = clWhite
    BackWall.Brush.Style = bsClear
    Title.Font.Charset = DEFAULT_CHARSET
    Title.Font.Color = clGreen
    Title.Font.Height = -11
    Title.Font.Name = 'Arial'
    Title.Font.Style = [fsBold]
    Title.Text.Strings = (
      'ny')
    BottomAxis.ExactDateTime = False
    BottomAxis.Increment = 0.2
    BottomAxis.LabelStyle = talValue
    LeftAxis.ExactDateTime = False
    LeftAxis.Increment = 0.01
    LeftAxis.LabelStyle = talValue
    Legend.Visible = False
    View3D = False
    TabOrder = 16
    object LineSeries4: TLineSeries
      Marks.ArrowLength = 8
      Marks.Visible = False
      SeriesColor = clRed
      LinePen.Width = 2
      Pointer.InflateMargins = True
      Pointer.Style = psRectangle
      Pointer.Visible = False
      XValues.DateTime = False
      XValues.Name = 'X'
      XValues.Multiplier = 1
      XValues.Order = loAscending
      YValues.DateTime = False
      YValues.Name = 'Y'
      YValues.Multiplier = 1
      YValues.Order = loNone
    end
  end
  object RadioButton11: TRadioButton
    Left = 456
    Top = 592
    Width = 113
    Height = 17
    Caption = 'W'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'MS Sans Serif'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 17
    OnClick = RadioButton11Click
  end
  object Chart11: TChart
    Left = 0
    Top = 0
    Width = 705
    Height = 553
    BackWall.Brush.Color = clWhite
    BackWall.Brush.Style = bsClear
    LeftWall.Color = clBlue
    Title.Font.Charset = DEFAULT_CHARSET
    Title.Font.Color = clGreen
    Title.Font.Height = -11
    Title.Font.Name = 'Arial'
    Title.Font.Style = [fsBold]
    Title.Text.Strings = (
      'W')
    BottomAxis.ExactDateTime = False
    BottomAxis.Increment = 0.2
    BottomAxis.LabelStyle = talValue
    LeftAxis.ExactDateTime = False
    LeftAxis.Increment = 0.01
    LeftAxis.LabelStyle = talValue
    Legend.Visible = False
    View3D = False
    TabOrder = 18
    object LineSeries5: TLineSeries
      Marks.ArrowLength = 8
      Marks.Visible = False
      SeriesColor = clRed
      LinePen.Width = 2
      Pointer.InflateMargins = True
      Pointer.Style = psRectangle
      Pointer.Visible = False
      XValues.DateTime = False
      XValues.Name = 'X'
      XValues.Multiplier = 1
      XValues.Order = loAscending
      YValues.DateTime = False
      YValues.Name = 'Y'
      YValues.Multiplier = 1
      YValues.Order = loNone
    end
  end
  object Chart1: TChart
    Left = 0
    Top = 0
    Width = 705
    Height = 553
    BackWall.Brush.Color = clWhite
    BackWall.Brush.Style = bsClear
    LeftWall.Color = clBlue
    Title.Font.Charset = DEFAULT_CHARSET
    Title.Font.Color = clGreen
    Title.Font.Height = -11
    Title.Font.Name = 'Arial'
    Title.Font.Style = [fsBold]
    Title.Text.Strings = (
      'r')
    BottomAxis.ExactDateTime = False
    BottomAxis.Increment = 0.2
    BottomAxis.LabelStyle = talValue
    LeftAxis.ExactDateTime = False
    LeftAxis.Increment = 0.01
    LeftAxis.LabelStyle = talValue
    Legend.Visible = False
    View3D = False
    TabOrder = 19
    object Series1: TLineSeries
      Marks.ArrowLength = 8
      Marks.Visible = False
      SeriesColor = clRed
      LinePen.Width = 2
      Pointer.InflateMargins = True
      Pointer.Style = psRectangle
      Pointer.Visible = False
      XValues.DateTime = False
      XValues.Name = 'X'
      XValues.Multiplier = 1
      XValues.Order = loAscending
      YValues.DateTime = False
      YValues.Name = 'Y'
      YValues.Multiplier = 1
      YValues.Order = loNone
    end
  end
end
